### ISSUE TITLE
Unified container: nv doesn't start

### ISSUE THREAD

**Issue by pcm32** [INRA/NMRProcFlow#3]
Hi @djacob65!

Because the Galaxy interactive environment can only run a single container, I had to add the elements for nv on the container we were building the other day:

https://github.com/phnmnl/nmrprocflow-ie

When I start the container, npflow works fine, I can upload then a zipped nmrml file and does the initial part fine, but when I go it processing, it give me an error with nv (doesn't know how to deal with the request).

You can replicate this like:

```
$ docker build -t pcm32/nmrprocflow-ie .
$ docker run -e DEBUG=false -P -p 8888:80 -it --entrypoint=bash pcm32/nmrprocflow-ie:latest
# then inside the container
$ /startup.sh &
```

and then point your browser to localhost:8888/npflow/ and go from there. I have installed php 5.6 as you use in the nv image, and followed equivalent steps to replicate the settings of the nv container in this unified container. PHP seems to be working fine, I just don't manage to see anything nv. Any thoughts? Thanks!

**Comment by djacob65** [comment]
Hi @pcm32 

I've found the issue and it works now !
1/ I modifed two files : Dockerfile & apache.conf  but I can't push it to github.
2/ it requires to initialize the PROXY_PREFIX (while my tests, i put an empty value).

Best,

**Comment by pcm32** [comment]
Great @djacob65! Can you make a PR at the other repo? or I can give you write access, whatever you prefer.

**Comment by pcm32** [comment]
ahhh, sorry, yes, when I tried it I had the PROXY_PREFIX, I just got rid of a number of env vars in the docker run that were unnecessary, and accidentally got rid of that :-(. But looking forward to the changes in (1).

**Comment by djacob65** [comment]
@ pcm32 I prefer to have write access if possible :-)

**Comment by djacob65** [comment]
@pcm32 I prefer to have write access if possible :-)

**Comment by pcm32** [comment]
Ok! I have done now, you should be able to write (sorry, I was on a call).

**Comment by djacob65** [comment]
@pcm32 
OK, I've pushed !

But I detect another issue : the upload_file_to_history.py  does not found the global variables => context issue.
The python script is launched from the 'R system' command.
I try to solve that !

**Comment by pcm32** [comment]
Great, thanks! We can modify the python part if needed to receive these things as arguments if needed. Let me know.

**Comment by djacob65** [comment]
@pcm32

Ok I solved this by modifying the python part as you suggested
See https://github.com/phnmnl/nmrprocflow-ie

**Comment by pcm32** [comment]
Excellent! I think we can close this now. Thanks for your help @djacob65!
